name: Auto Assign
on:
  pull_request:
    types: [ready_for_review]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: 'Auto-assign'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ssec-jhu/team
          numOfAssignee: 1
