name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    name: lint with ruff with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements/dev.txt
        shell: bash
      - name: Lint
        run: tox -e check-style
        shell: bash

  test:
    name: pytests on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
      with:
          lfs: true
          fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements/dev.txt
      shell: bash
    - name: pip install package
      run: pip install .
    - name: Test with tox (pytest)
      run: tox -e test
    - name: Extract coverage information
      id: cov_outputs
      run: python coverage_writer.py
    - name: Archive coverage report
      uses: actions/upload-artifact@v4.4.3
      with:
        name: code-coverage-report-python${{ matrix.python-version }}-${{ matrix.os }}
        path: coverage.xml
        retention-days: 14
        if-no-files-found: error
    - name: Evaluate Codebase Coverage
      uses: 5monkeys/cobertura-action@v14
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        path: coverage.xml
        minimum_coverage: 90
        fail_below_threshold: true
    - name: Evaluate Patch Coverage
      if: github.event_name == 'pull_request'
      id: diff-coverage
      uses: Affanmir/diff-cover-action@v2.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coverage-files: coverage.xml
        config-file: pyproject.toml
        create-annotations: true
    - name: Generate and Commit Coverage Badge
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: jaywcjlove/generated-badges@v1.1.0
      with:
        label: Coverage
        output: coverage.svg
        status: ${{ steps.cov_outputs.outputs.percent }}
        color: ${{ steps.cov_outputs.outputs.color }}
    - name: Commit coverage badge
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v7.1.0
      with:
        commit_message: "[skip ci] Update coverage badge"
        file_pattern: coverage.svg
        branch: badges
        commit_options: '--no-verify --signoff'

  docs:
    name: Build docs with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    # need permissions to deploy to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install tox
        run: python -m pip install tox
        shell: bash
      - name: Build sphinx docs.
        # Comment the env: SPHINXOPTS if you want to ignore warnings during doc build
        env:
         SPHINXOPTS: '-W'
        run: tox -e build-docs
        shell: bash
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          path: ./docs/_build/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  build:
    name: Build and Publish.
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
